version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 10
    versioning-strategy: widen

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
